# Generated by Django 3.1.5 on 2021-01-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WebIndexing',
            new_name='WIModel',
        ),
    ]
